CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(100) UNIQUE,
    stock_count INT NOT NULL DEFAULT 0,
    min_stock_level INT NOT NULL DEFAULT 10,
    price DECIMAL(12, 2) DEFAULT 0.00,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated users"
ON public.categories FOR ALL TO authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for service role"
ON public.categories FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for authenticated users"
ON public.products FOR ALL TO authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for service role"
ON public.products FOR ALL TO service_role
USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.products;

-- Seed Data
INSERT INTO public.categories (name, description) VALUES
('T-Shirts', 'Berbagai jenis kaos dan t-shirt'),
('Jeans', 'Celana jeans denim dan sejenisnya'),
('Sneakers', 'Sepatu olahraga dan kasual');

INSERT INTO public.products (category_id, name, sku, stock_count, min_stock_level, price) VALUES
(1, 'T-Shirt - Small', 'TS-SML-01', 50, 15, 75000),
(2, 'Jeans - Blue', 'JN-BLU-01', 25, 10, 250000),
(3, 'Sneakers - Black', 'SN-BLK-01', 12, 10, 450000);